# Generated by Django 4.2.9 on 2026-01-18 12:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("medications", "0005_alter_prescription_route"),
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "appointment_datetime",
                    models.DateTimeField(help_text="Date and time of the appointment"),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("follow_up", "Follow-up Visit"),
                            ("medication_review", "Medication Review"),
                            ("consultation", "Consultation"),
                            ("emergency", "Emergency"),
                            ("routine_checkup", "Routine Checkup"),
                        ],
                        help_text="Type of appointment",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        help_text="Current status of the appointment",
                        max_length=20,
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital Visit"),
                            ("home_visit", "Home Visit"),
                            ("telemedicine", "Telemedicine"),
                        ],
                        default="hospital",
                        help_text="Where the appointment will take place",
                        max_length=20,
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the healthcare provider",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, help_text="Department or specialty", max_length=100, null=True
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for the appointment", null=True),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes in English", null=True
                    ),
                ),
                (
                    "notes_kinyarwanda",
                    models.TextField(
                        blank=True, help_text="Additional notes in Kinyarwanda", null=True
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Expected duration in minutes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discharge_summary",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related discharge summary if this is a follow-up appointment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_up_appointments",
                        to="enrollment.dischargesummary",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        help_text="The hospital or facility for this appointment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="enrollment.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="The patient for this appointment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related prescription if this is a medication review",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_appointments",
                        to="medications.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["appointment_datetime"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reminder_datetime", models.DateTimeField(help_text="When to send the reminder")),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("call", "Phone Call"),
                        ],
                        default="sms",
                        help_text="Type of reminder",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Status of the reminder",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Custom reminder message in English", null=True
                    ),
                ),
                (
                    "message_kinyarwanda",
                    models.TextField(
                        blank=True, help_text="Custom reminder message in Kinyarwanda", null=True
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When the reminder was actually sent", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if sending failed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        help_text="The appointment this reminder is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Reminder",
                "verbose_name_plural": "Appointment Reminders",
                "ordering": ["reminder_datetime"],
                "indexes": [
                    models.Index(
                        fields=["reminder_datetime", "status"],
                        name="appointment_reminde_3123ef_idx",
                    ),
                    models.Index(fields=["appointment"], name="appointment_appoint_265f9f_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_datetime"], name="appointment_appoint_ff6788_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="appointment_status_8fe9d7_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "appointment_datetime"], name="appointment_patient_6bcbef_idx"
            ),
        ),
    ]
