# Generated by Django 4.2.9 on 2026-01-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancellation_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for cancellation if appointment was cancelled",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, help_text="When the appointment was cancelled", null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancelled_by",
            field=models.CharField(
                blank=True,
                choices=[("patient", "Patient"), ("nurse", "Nurse"), ("system", "System")],
                help_text="Who cancelled the appointment",
                max_length=50,
                null=True,
            ),
        ),
    ]
