# Generated by Django 6.0.1 on 2026-01-28 16:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0002_patient_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caregiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: +250XXXXXXXXX",
                                regex="^\\+250\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("registered_nurse", "Registered Nurse"),
                            ("licensed_practical_nurse", "Licensed Practical Nurse"),
                            (
                                "certified_nursing_assistant",
                                "Certified Nursing Assistant",
                            ),
                            ("home_health_aide", "Home Health Aide"),
                            ("personal_care_aide", "Personal Care Aide"),
                            ("companion", "Companion Caregiver"),
                        ],
                        max_length=50,
                    ),
                ),
                ("license_number", models.CharField(blank=True, max_length=100)),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ]
                    ),
                ),
                ("bio", models.TextField(help_text="Professional bio and experience")),
                ("province", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("sector", models.CharField(blank=True, max_length=50)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False)),
                ("background_check_completed", models.BooleanField(default=False)),
                ("background_check_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-rating", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaregiverBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_type", models.CharField(max_length=100)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("duration_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("location_address", models.TextField()),
                ("location_notes", models.TextField(blank=True)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("patient_notes", models.TextField(blank=True)),
                ("caregiver_notes", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("cancelled_by", models.CharField(blank=True, max_length=20)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="caregivers.caregiver",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_bookings",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="CaregiverCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certification_name", models.CharField(max_length=200)),
                ("issuing_organization", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="caregivers.caregiver",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="CaregiverReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="caregivers.caregiverbooking",
                    ),
                ),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="caregivers.caregiver",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_reviews",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaregiverService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="caregivers.caregiver",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="caregiver",
            index=models.Index(
                fields=["availability_status", "is_active"],
                name="caregivers__availab_ae2be0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="caregiver",
            index=models.Index(
                fields=["province", "district"], name="caregivers__provinc_cb21b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caregiver",
            index=models.Index(
                fields=["-rating"], name="caregivers__rating_6172cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caregiverbooking",
            index=models.Index(
                fields=["patient", "status"], name="caregivers__patient_f0cbc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caregiverbooking",
            index=models.Index(
                fields=["caregiver", "status"], name="caregivers__caregiv_ba9478_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caregiverbooking",
            index=models.Index(
                fields=["start_datetime"], name="caregivers__start_d_d40cc8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="caregiverservice",
            unique_together={("caregiver", "service_name")},
        ),
    ]
