# Generated by Django 4.2.9 on 2026-01-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique template identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("appointment_reminder", "Appointment Reminder"),
                            ("medication_reminder", "Medication Reminder"),
                            ("general_notification", "General Notification"),
                            ("emergency_alert", "Emergency Alert"),
                            ("survey", "Survey"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("sms", "SMS"), ("whatsapp", "WhatsApp")], max_length=20
                    ),
                ),
                (
                    "content_english",
                    models.TextField(
                        help_text="Message content in English with placeholders {variable_name}"
                    ),
                ),
                (
                    "content_kinyarwanda",
                    models.TextField(
                        blank=True,
                        help_text="Message content in Kinyarwanda with placeholders",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this template is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["template_type", "message_type"],
                        name="messaging_m_templat_bb89d8_idx",
                    ),
                    models.Index(fields=["is_active"], name="messaging_m_is_acti_443b8a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(help_text="Phone number with country code", max_length=20),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("sms", "SMS"), ("whatsapp", "WhatsApp")], max_length=20
                    ),
                ),
                ("content", models.TextField(help_text="Final rendered message content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_send_time",
                    models.DateTimeField(
                        blank=True, help_text="When to send the message", null=True
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When message was actually sent", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "recipient_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="patients.patient",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="messaging.messagetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("recipient_phone", models.CharField(max_length=20)),
                (
                    "message_type",
                    models.CharField(
                        choices=[("sms", "SMS"), ("whatsapp", "WhatsApp")], max_length=20
                    ),
                ),
                ("content", models.TextField()),
                ("scheduled_time", models.DateTimeField(help_text="When to send this message")),
                ("template_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "context_data",
                    models.JSONField(
                        blank=True, help_text="Template variables for rendering", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queued_messages",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "sent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queue_entry",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "scheduled_time"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_time"], name="messaging_m_status_b23d21_idx"
                    ),
                    models.Index(
                        fields=["priority", "scheduled_time"], name="messaging_m_priorit_7487ad_idx"
                    ),
                    models.Index(fields=["appointment"], name="messaging_m_appoint_02601e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Message ID from Africa's Talking",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "provider_response",
                    models.TextField(
                        blank=True, help_text="Full response from Africa's Talking API", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if delivery failed", null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Cost of sending the message",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="Currency code (USD, RWF, etc.)", max_length=3
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["message", "-timestamp"], name="messaging_m_message_f1cb77_idx"
                    ),
                    models.Index(fields=["status"], name="messaging_m_status_cdf57d_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["recipient_patient", "status"], name="messaging_m_recipie_80f76f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["status", "scheduled_send_time"], name="messaging_m_status_29bd23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["-created_at"], name="messaging_m_created_707554_idx"),
        ),
    ]
