# Generated by Django 4.2.9 on 2026-01-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Commercial/brand name of the medication", max_length=200
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(
                        help_text="Generic/scientific name of the medication", max_length=200
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        blank=True,
                        help_text="Brand name if different from name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "dosage_form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("syrup", "Syrup"),
                            ("injection", "Injection"),
                            ("cream", "Cream"),
                            ("ointment", "Ointment"),
                            ("drops", "Drops"),
                            ("inhaler", "Inhaler"),
                            ("patch", "Patch"),
                            ("suppository", "Suppository"),
                        ],
                        help_text="Form of the medication (tablet, syrup, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        help_text="Strength of the medication (e.g., 500mg, 5ml)", max_length=100
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer of the medication",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="General description of the medication", null=True
                    ),
                ),
                (
                    "indication",
                    models.TextField(
                        blank=True, help_text="What the medication is used for", null=True
                    ),
                ),
                (
                    "contraindications",
                    models.TextField(
                        blank=True, help_text="When the medication should not be used", null=True
                    ),
                ),
                (
                    "side_effects",
                    models.TextField(blank=True, help_text="Common side effects", null=True),
                ),
                (
                    "storage_instructions",
                    models.TextField(
                        blank=True, help_text="How to store the medication", null=True
                    ),
                ),
                (
                    "requires_prescription",
                    models.BooleanField(
                        default=False, help_text="Whether the medication requires a prescription"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the medication is currently available"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "medication",
                "verbose_name_plural": "medications",
                "ordering": ["name"],
            },
        ),
    ]
