# Generated by Django 4.2.9 on 2026-01-15 19:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0001_initial"),
        ("patients", "__first__"),
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        help_text="Dosage amount (e.g., 500mg, 2 tablets, 5ml)", max_length=100
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="How often to take (e.g., twice daily, every 8 hours)",
                        max_length=100,
                    ),
                ),
                (
                    "frequency_times_per_day",
                    models.PositiveIntegerField(
                        help_text="Number of times per day to take medication",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("oral", "Oral"),
                            ("topical", "Topical"),
                            ("intravenous", "Intravenous (IV)"),
                            ("intramuscular", "Intramuscular (IM)"),
                            ("subcutaneous", "Subcutaneous"),
                            ("inhalation", "Inhalation"),
                            ("rectal", "Rectal"),
                            ("transdermal", "Transdermal"),
                        ],
                        default="oral",
                        help_text="Route of administration",
                        max_length=20,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        help_text="Duration of treatment in days",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total quantity prescribed", null=True
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Special instructions in English (e.g., take with food)",
                        null=True,
                    ),
                ),
                (
                    "instructions_kinyarwanda",
                    models.TextField(
                        blank=True, help_text="Special instructions in Kinyarwanda", null=True
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Date to start taking medication", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Date to stop taking medication", null=True
                    ),
                ),
                (
                    "prescribed_by",
                    models.CharField(
                        blank=True,
                        help_text="Name of prescribing physician",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "refills_allowed",
                    models.PositiveIntegerField(default=0, help_text="Number of refills allowed"),
                ),
                (
                    "refills_remaining",
                    models.PositiveIntegerField(default=0, help_text="Number of refills remaining"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this prescription is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discharge_summary",
                    models.ForeignKey(
                        blank=True,
                        help_text="The discharge summary this prescription is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="enrollment.dischargesummary",
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        help_text="The prescribed medication",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="medications.medication",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="The patient this prescription is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "prescription",
                "verbose_name_plural": "prescriptions",
                "ordering": ["-created_at"],
            },
        ),
    ]
