# Generated by Django 4.2.9 on 2026-01-15 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "__first__"),
        ("medications", "0002_prescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationAdherence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date the medication should be taken",
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(help_text="Time the medication should be taken"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("taken", "Taken"),
                            ("missed", "Missed"),
                            ("skipped", "Skipped"),
                            ("late", "Late"),
                        ],
                        default="scheduled",
                        help_text="Status of this medication dose",
                        max_length=20,
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(
                        blank=True, help_text="When the medication was actually taken", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this dose", null=True
                    ),
                ),
                (
                    "reason_missed",
                    models.CharField(
                        blank=True,
                        help_text="Reason why medication was missed or skipped",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, help_text="Whether a reminder was sent for this dose"
                    ),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When the reminder was sent", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="The patient this adherence record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adherence_records",
                        to="patients.patient",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        help_text="The prescription this adherence record is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adherence_records",
                        to="medications.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "medication adherence",
                "verbose_name_plural": "medication adherence records",
                "ordering": ["-scheduled_date", "-scheduled_time"],
                "unique_together": {("prescription", "scheduled_date", "scheduled_time")},
            },
        ),
    ]
