# Generated by Django 4.2.9 on 2026-01-15 19:44

import apps.medications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0003_medicationadherence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicationadherence",
            name="scheduled_date",
            field=models.DateField(
                default=apps.medications.models.get_current_date,
                help_text="Date the medication should be taken",
            ),
        ),
    ]
