# Generated by Django 4.2.9 on 2026-01-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0004_alter_medicationadherence_scheduled_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="route",
            field=models.CharField(
                choices=[
                    ("oral", "Oral"),
                    ("topical", "Topiucal"),
                    ("intravenous", "Intravenous (IV)"),
                    ("intramuscular", "Intramuscular (IM)"),
                    ("subcutaneous", "Subcutaneous"),
                    ("inhalation", "Inhalation"),
                    ("rectal", "Rectal"),
                    ("transdermal", "Transdermal"),
                ],
                default="oral",
                help_text="Route of administration",
                max_length=20,
            ),
        ),
    ]
