# Generated by Django 4.2.9 on 2026-01-25 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medications", "0005_alter_prescription_route"),
    ]

    operations = [
        migrations.CreateModel(
            name="SymptomReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "symptom_type",
                    models.CharField(
                        choices=[
                            ("side_effect", "Medication Side Effect"),
                            ("symptom", "General Symptom"),
                            ("pain", "Pain"),
                            ("fatigue", "Fatigue"),
                            ("nausea", "Nausea"),
                            ("dizziness", "Dizziness"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                ("trigger", models.CharField(blank=True, max_length=200, null=True)),
                ("reviewed_by_nurse", models.BooleanField(default=False)),
                ("nurse_response", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptom_reports",
                        to="patients.patient",
                    ),
                ),
                (
                    "related_prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="symptom_reports",
                        to="medications.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "reported_at"], name="medications_patient_0b61d7_idx"
                    ),
                    models.Index(fields=["symptom_type"], name="medications_symptom_9dd9e2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionRefillRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity_requested", models.PositiveIntegerField()),
                ("reason", models.TextField(blank=True, null=True)),
                ("urgent", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refill_requests",
                        to="patients.patient",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refill_requests",
                        to="medications.prescription",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_refill_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "status"], name="medications_patient_9a0352_idx"
                    ),
                    models.Index(
                        fields=["prescription", "requested_at"],
                        name="medications_prescri_6c35a3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientMedicationTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("taken", "Taken"),
                            ("missed", "Missed"),
                            ("delayed", "Delayed"),
                            ("not_reported", "Not Reported"),
                        ],
                        default="not_reported",
                        max_length=20,
                    ),
                ),
                ("taken_time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_tracking",
                        to="patients.patient",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_records",
                        to="medications.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["patient", "date"], name="medications_patient_cdc7f3_idx"),
                    models.Index(
                        fields=["prescription", "date"], name="medications_prescri_c74047_idx"
                    ),
                ],
                "unique_together": {("patient", "prescription", "date")},
            },
        ),
    ]
