# Generated by Django 4.2.9 on 2026-01-18 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "allow_data_export",
                    models.BooleanField(
                        default=True, help_text="Allow patient to export their data"
                    ),
                ),
                (
                    "allow_marketing_communications",
                    models.BooleanField(default=False, help_text="Allow marketing communications"),
                ),
                (
                    "allow_research_participation",
                    models.BooleanField(
                        default=False, help_text="Allow participation in research studies"
                    ),
                ),
                (
                    "allow_third_party_sharing",
                    models.BooleanField(
                        default=False, help_text="Allow sharing data with third parties"
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("phone", "Phone Call"),
                            ("none", "No Contact"),
                        ],
                        default="email",
                        help_text="Preferred method of contact",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        help_text="The patient these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_preference",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Privacy Preference",
                "verbose_name_plural": "Privacy Preferences",
            },
        ),
        migrations.CreateModel(
            name="ConsentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("data_processing", "Data Processing"),
                            ("marketing", "Marketing Communications"),
                            ("research", "Research Participation"),
                            ("data_sharing", "Data Sharing"),
                        ],
                        help_text="Type of consent",
                        max_length=50,
                    ),
                ),
                (
                    "version_number",
                    models.CharField(help_text="Version number (e.g., 1.0, 2.0)", max_length=20),
                ),
                (
                    "effective_date",
                    models.DateField(help_text="Date when this version becomes effective"),
                ),
                ("content_english", models.TextField(help_text="Consent text in English")),
                (
                    "content_kinyarwanda",
                    models.TextField(
                        blank=True, help_text="Consent text in Kinyarwanda", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this version is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consent Version",
                "verbose_name_plural": "Consent Versions",
                "ordering": ["consent_type", "version_number"],
                "indexes": [
                    models.Index(
                        fields=["consent_type", "is_active"], name="consents_co_consent_fa1048_idx"
                    ),
                    models.Index(fields=["effective_date"], name="consents_co_effecti_41c2d9_idx"),
                ],
                "unique_together": {("consent_type", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "granted",
                    models.BooleanField(
                        default=True, help_text="Whether consent is granted or revoked"
                    ),
                ),
                ("granted_date", models.DateTimeField(help_text="When consent was granted")),
                (
                    "revoked_date",
                    models.DateTimeField(
                        blank=True, help_text="When consent was revoked (if applicable)", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the consent", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address from which consent was given", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent_version",
                    models.ForeignKey(
                        help_text="The version of consent that was agreed to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consents",
                        to="consents.consentversion",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="The patient who gave consent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent",
                "verbose_name_plural": "Consents",
                "ordering": ["-granted_date"],
            },
        ),
        migrations.CreateModel(
            name="ConsentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("granted", "Consent Granted"),
                            ("revoked", "Consent Revoked"),
                            ("updated", "Consent Updated"),
                            ("viewed", "Consent Viewed"),
                            ("exported", "Data Exported"),
                        ],
                        help_text="Action performed",
                        max_length=20,
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        help_text="Who performed the action (user, system, patient, admin)",
                        max_length=200,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When the action was performed"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="Additional details about the action", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which action was performed",
                        null=True,
                    ),
                ),
                (
                    "consent",
                    models.ForeignKey(
                        help_text="The consent this log entry is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="consents.consent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Audit Log",
                "verbose_name_plural": "Consent Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["consent", "timestamp"], name="consents_co_consent_f4eca1_idx"
                    ),
                    models.Index(
                        fields=["action", "timestamp"], name="consents_co_action_daeaca_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="consent",
            index=models.Index(
                fields=["patient", "consent_version"], name="consents_co_patient_3871c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consent",
            index=models.Index(
                fields=["granted", "granted_date"], name="consents_co_granted_0aeaaa_idx"
            ),
        ),
    ]
