# Generated by Django 4.2.9 on 2026-01-18 12:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("first_name_kinyarwanda", models.CharField(blank=True, max_length=100)),
                ("last_name_kinyarwanda", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=1
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="National ID must be exactly 16 digits", regex="^\\d{16}$"
                            )
                        ],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: +250XXXXXXXXX",
                                regex="^\\+250\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "alt_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: +250XXXXXXXXX",
                                regex="^\\+250\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("enrolled_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prefers_sms", models.BooleanField(default=True)),
                ("prefers_whatsapp", models.BooleanField(default=False)),
                (
                    "language_preference",
                    models.CharField(
                        choices=[("kin", "Kinyarwanda"), ("eng", "English"), ("fra", "French")],
                        default="kin",
                        max_length=10,
                    ),
                ),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrolled_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["-enrolled_date"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                            ("friend", "Friend"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: +250XXXXXXXXX",
                                regex="^\\+250\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "alt_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: +250XXXXXXXXX",
                                regex="^\\+250\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
                "ordering": ["-is_primary", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("province", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("sector", models.CharField(max_length=50)),
                ("cell", models.CharField(max_length=50)),
                ("village", models.CharField(max_length=50)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("street_address", models.TextField(blank=True)),
                (
                    "landmarks",
                    models.TextField(blank=True, help_text="Nearby landmarks for navigation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["national_id"], name="patients_pa_nationa_70cc77_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["phone_number"], name="patients_pa_phone_n_933975_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["-enrolled_date"], name="patients_pa_enrolle_6afcbf_idx"),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["province", "district"], name="patients_ad_provinc_1ec3e2_idx"
            ),
        ),
    ]
