# Generated by Django 4.2.9 on 2026-01-27 17:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0002_patient_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "vital_type",
                    models.CharField(
                        choices=[
                            ("blood_pressure", "Blood Pressure"),
                            ("heart_rate", "Heart Rate"),
                            ("temperature", "Temperature"),
                            ("weight", "Weight"),
                            ("oxygen_saturation", "Oxygen Saturation"),
                            ("respiratory_rate", "Respiratory Rate"),
                            ("blood_glucose", "Blood Glucose"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "goal_name",
                    models.CharField(
                        help_text="Name of the goal (e.g., 'Reduce blood pressure')", max_length=255
                    ),
                ),
                ("target_value", models.FloatField(help_text="Target value to achieve")),
                ("unit", models.CharField(help_text="Unit of measurement", max_length=20)),
                ("start_date", models.DateField()),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("achieved", "Achieved"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_goals",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VitalReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reading_type",
                    models.CharField(
                        choices=[
                            ("blood_pressure", "Blood Pressure"),
                            ("heart_rate", "Heart Rate"),
                            ("temperature", "Temperature"),
                            ("weight", "Weight"),
                            ("oxygen_saturation", "Oxygen Saturation"),
                            ("respiratory_rate", "Respiratory Rate"),
                            ("blood_glucose", "Blood Glucose"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recorded_at", models.DateTimeField()),
                (
                    "value",
                    models.FloatField(
                        help_text="Numeric value of the reading (unit depends on reading type)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "secondary_value",
                    models.FloatField(
                        blank=True,
                        help_text="Secondary value (e.g., diastolic for blood pressure)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement (e.g., bpm, mmHg, °C, kg, %)", max_length=20
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional clinical notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_readings",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_vitals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-recorded_at"], name="vitals_vita_patient_1c6a53_idx"
                    ),
                    models.Index(
                        fields=["reading_type", "-recorded_at"],
                        name="vitals_vita_reading_d3d8c0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "vital_type",
                    models.CharField(
                        choices=[
                            ("blood_pressure", "Blood Pressure"),
                            ("heart_rate", "Heart Rate"),
                            ("temperature", "Temperature"),
                            ("weight", "Weight"),
                            ("oxygen_saturation", "Oxygen Saturation"),
                            ("respiratory_rate", "Respiratory Rate"),
                            ("blood_glucose", "Blood Glucose"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "reading_count",
                    models.IntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("average_value", models.FloatField(blank=True, null=True)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("median_value", models.FloatField(blank=True, null=True)),
                ("average_secondary_value", models.FloatField(blank=True, null=True)),
                ("min_secondary_value", models.FloatField(blank=True, null=True)),
                ("max_secondary_value", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(max_length=20)),
                (
                    "trend_direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("improving", "Improving"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_trends",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end"],
                "indexes": [
                    models.Index(
                        fields=["patient", "vital_type", "-period_end"],
                        name="vitals_heal_patient_7e60ac_idx",
                    )
                ],
                "unique_together": {("patient", "vital_type", "period", "period_start")},
            },
        ),
    ]
