# Generated by Django 6.0.1 on 2026-03-06 14:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_user'),
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Goal title (e.g., 'Drink 8 glasses of water')", max_length=200)),
                ('category', models.CharField(choices=[('exercise', 'Exercise'), ('hydration', 'Hydration'), ('medication', 'Medication'), ('nutrition', 'Nutrition'), ('sleep', 'Sleep'), ('meditation', 'Meditation/Mindfulness'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('target_value', models.IntegerField(help_text='Target number to achieve daily (e.g., 8 for 8 glasses)', validators=[django.core.validators.MinValueValidator(1)])),
                ('current_value', models.IntegerField(default=0, help_text='Current progress for today', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=True, help_text='If true, goal repeats on specified days')),
                ('recurrence_days', models.JSONField(default=list, help_text='List of weekday numbers (0=Mon, 6=Sun) when goal is active')),
                ('reminder_time', models.TimeField(blank=True, help_text='Time to send daily reminder (if set)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date this progress record is for')),
                ('completed', models.BooleanField(default=False)),
                ('actual_value', models.IntegerField(default=0, help_text='Actual progress achieved', validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='vitals.dailygoal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='dailygoal',
            index=models.Index(fields=['patient', '-created_at'], name='vitals_dail_patient_747e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='dailygoal',
            index=models.Index(fields=['patient', 'is_completed'], name='vitals_dail_patient_a77331_idx'),
        ),
        migrations.AddIndex(
            model_name='goalprogress',
            index=models.Index(fields=['goal', '-date'], name='vitals_goal_goal_id_544cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='goalprogress',
            index=models.Index(fields=['date', 'completed'], name='vitals_goal_date_edec1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goalprogress',
            unique_together={('goal', 'date')},
        ),
    ]
