# Generated by Django 4.2.9 on 2026-01-19 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0001_initial"),
        ("appointments", "0001_initial"),
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NurseProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("specialization", models.CharField(blank=True, max_length=100)),
                (
                    "current_shift",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "Morning (6AM-2PM)"),
                            ("afternoon", "Afternoon (2PM-10PM)"),
                            ("night", "Night (10PM-6AM)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("on_break", "On Break"),
                            ("off_duty", "Off Duty"),
                        ],
                        default="off_duty",
                        max_length=20,
                    ),
                ),
                ("max_concurrent_patients", models.IntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurse_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="PatientAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("missed_medication", "Missed Medication"),
                            ("missed_appointment", "Missed Appointment"),
                            ("high_risk_discharge", "High Risk Discharge"),
                            ("symptom_report", "Symptom Report"),
                            ("readmission_risk", "Readmission Risk"),
                            ("medication_side_effect", "Medication Side Effect"),
                            ("emergency", "Emergency"),
                            ("follow_up_needed", "Follow-up Needed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("sla_deadline", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("escalation_reason", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "assigned_nurse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_alerts",
                        to="nursing.nurseprofile",
                    ),
                ),
                (
                    "discharge_summary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="enrollment.dischargesummary",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NursePatientAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("transferred", "Transferred"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("last_contact_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "discharge_summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurse_assignments",
                        to="enrollment.dischargesummary",
                    ),
                ),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_assignments",
                        to="nursing.nurseprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurse_assignments",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("assigned", "Assigned"),
                            ("acknowledged", "Acknowledged"),
                            ("updated", "Updated"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                            ("closed", "Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="nursing.patientalert",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="patientalert",
            index=models.Index(fields=["status", "severity"], name="nursing_pat_status_0182b4_idx"),
        ),
        migrations.AddIndex(
            model_name="patientalert",
            index=models.Index(fields=["patient", "status"], name="nursing_pat_patient_0e5f75_idx"),
        ),
        migrations.AddIndex(
            model_name="patientalert",
            index=models.Index(
                fields=["assigned_nurse", "status"], name="nursing_pat_assigne_6544de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientalert",
            index=models.Index(fields=["created_at"], name="nursing_pat_created_bed1a3_idx"),
        ),
        migrations.AddIndex(
            model_name="nursepatientassignment",
            index=models.Index(fields=["nurse", "status"], name="nursing_nur_nurse_i_52f8ba_idx"),
        ),
        migrations.AddIndex(
            model_name="nursepatientassignment",
            index=models.Index(fields=["patient", "status"], name="nursing_nur_patient_770263_idx"),
        ),
    ]
