# Generated by Django 4.2.9 on 2026-01-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0001_initial"),
        ("nursing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nursepatientassignment",
            name="discharge_summary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nurse_assignments",
                to="enrollment.dischargesummary",
            ),
        ),
    ]
