# Generated by Django 4.2.9 on 2026-01-12 15:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique hospital code (e.g., CHUK, KFH)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "hospital_type",
                    models.CharField(
                        choices=[
                            ("referral", "Referral Hospital"),
                            ("district", "District Hospital"),
                            ("health_center", "Health Center"),
                            ("clinic", "Clinic"),
                        ],
                        default="district",
                        max_length=50,
                    ),
                ),
                ("province", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("sector", models.CharField(blank=True, max_length=50)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: +250XXXXXXXXX",
                                regex="^\\+250\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "emr_integration_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("api", "API Integration"),
                            ("hl7", "HL7 Integration"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                (
                    "emr_system_name",
                    models.CharField(blank=True, help_text="e.g., OpenMRS, DHIS2", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pilot", "Pilot Program"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hospital",
                "verbose_name_plural": "Hospitals",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DischargeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("admission_date", models.DateField()),
                ("discharge_date", models.DateField()),
                ("length_of_stay_days", models.PositiveIntegerField(editable=False)),
                ("primary_diagnosis", models.TextField(help_text="Main diagnosis for admission")),
                (
                    "secondary_diagnoses",
                    models.TextField(
                        blank=True, help_text="Additional diagnoses (comma-separated or free text)"
                    ),
                ),
                ("icd10_primary", models.CharField(blank=True, max_length=10)),
                ("icd10_secondary", models.CharField(blank=True, max_length=200)),
                (
                    "procedures_performed",
                    models.TextField(
                        blank=True, help_text="Surgeries, procedures, interventions performed"
                    ),
                ),
                (
                    "treatment_summary",
                    models.TextField(help_text="Overview of treatment provided during stay"),
                ),
                (
                    "discharge_condition",
                    models.CharField(
                        choices=[
                            ("improved", "Improved"),
                            ("stable", "Stable"),
                            ("unchanged", "Unchanged"),
                            ("deteriorated", "Deteriorated"),
                        ],
                        default="improved",
                        max_length=50,
                    ),
                ),
                (
                    "discharge_instructions",
                    models.TextField(
                        help_text="Instructions for patient and family in patient's language"
                    ),
                ),
                ("discharge_instructions_kinyarwanda", models.TextField(blank=True)),
                (
                    "diet_instructions",
                    models.TextField(
                        blank=True, help_text="Special dietary requirements or restrictions"
                    ),
                ),
                (
                    "activity_restrictions",
                    models.TextField(blank=True, help_text="Physical activity limitations"),
                ),
                ("follow_up_required", models.BooleanField(default=True)),
                (
                    "follow_up_timeframe",
                    models.CharField(
                        blank=True, help_text="e.g., '1 week', '2 weeks', '1 month'", max_length=50
                    ),
                ),
                (
                    "follow_up_with",
                    models.CharField(
                        blank=True, help_text="Which department or specialist", max_length=200
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Risk of readmission or complications",
                        max_length=20,
                    ),
                ),
                (
                    "risk_factors",
                    models.TextField(
                        blank=True,
                        help_text="Specific risk factors identified (e.g., social determinants, compliance concerns)",
                    ),
                ),
                (
                    "warning_signs",
                    models.TextField(
                        blank=True,
                        help_text="Symptoms that should prompt immediate medical attention",
                    ),
                ),
                ("warning_signs_kinyarwanda", models.TextField(blank=True)),
                ("attending_physician", models.CharField(max_length=200)),
                ("discharge_nurse", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "additional_notes",
                    models.TextField(blank=True, help_text="Any other relevant information"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_discharge_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discharge_summaries",
                        to="enrollment.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_summaries",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discharge Summary",
                "verbose_name_plural": "Discharge Summaries",
                "ordering": ["-discharge_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "discharge_date"], name="enrollment__patient_115e8e_idx"
                    ),
                    models.Index(
                        fields=["hospital", "discharge_date"], name="enrollment__hospita_fcc92a_idx"
                    ),
                    models.Index(fields=["risk_level"], name="enrollment__risk_le_3cacf6_idx"),
                ],
            },
        ),
    ]
